//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clgProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persondata
    {
        public string name { get; set; }
        public string accountNo { get; set; }
        public string aadharNo { get; set; }
        public string branch { get; set; }
    }
}
